### ISSUE TITLE
Error: CSS minification error: Cannot read property 'length' of undefined.

### ISSUE THREAD

**Issue by Srilakshmijayaraju** [somteacodes/weatherappvue#1]
When tried to run " npm run build " getting below err

 ERROR  Error: CSS minification error: Cannot read property 'length' of undefined. File: css/app.9020724b.css
Error: CSS minification error: Cannot read property 'length' of undefined. File: css/app.9020724b.css
    at /Users/a299286/IdeaProjects/weatherappvue/node_modules/@intervolga/optimize-cssnano-plugin/index.js:106:21
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async Promise.all (index 0)

**Comment by somteacodes** [comment]
Bug was from the CSS linear-gradient function. In development, I could use CSS variables to define the direction of gradient, but in production it failed.
Fixed issue by just specifying the direction for the gradient rather then using a CSS variable to do so.
